//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XPOSample02.Models
{

  public partial class Music : XPObject
  {
    string _title;
    public string Title
    {
      get { return _title; }
      set { SetPropertyValue<string>("Title", ref _title, value); }
    }
    string _artistName;
    public string ArtistName
    {
      get { return _artistName; }
      set { SetPropertyValue<string>("ArtistName", ref _artistName, value); }
    }
  }

}
